/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_handsome_ffmpegdouyin_FFmpeg_FFmpegRun */

#ifndef _Included_com_handsome_ffmpegdouyin_FFmpeg_FFmpegRun
#define _Included_com_handsome_ffmpegdouyin_FFmpeg_FFmpegRun
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_handsome_ffmpegdouyin_FFmpeg_FFmpegRun
 * Method:    run
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_handsome_ffmpegdouyin_FFmpeg_FFmpegRun_run
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
